spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_project?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security : debug
#  org.hibernate.type: trace


## test 환경

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo-testㅁ
    username: sa
    password:
    driver-class-name: org.h2.Driver
